# Generated by Django 3.2.5 on 2021-08-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=7, null=True)),
                ('date_started', models.DateField(null=True)),
                ('syllabus', models.TextField(null=True)),
                ('course_id', models.CharField(max_length=3, null=True)),
                ('course_code', models.CharField(max_length=7, null=True)),
                ('course_duration', models.CharField(max_length=3, null=True)),
            ],
        ),
    ]
